const DEV_PORT = process.env.WRANGLER_DEV_PORT ?? "8788";
export const BASE_URL = `http://127.0.0.1:${DEV_PORT}`;

/**
 * Wrapper around fetch that attaches the test session JWT as a cookie.
 * The token is generated by scripts/test-with-server.mjs before vitest starts.
 */
export function authFetch(url, options = {}) {
  const token = process.env.TEST_SESSION_TOKEN;
  if (!token) {
    throw new Error(
      "TEST_SESSION_TOKEN is not set – run integration tests via `npm run test:integration`",
    );
  }

  const headers = { ...options.headers, Cookie: `session=${token}` };
  return fetch(url, { ...options, headers });
}
