-- Sandra: For seed, specify values that are usually autogenerated for testing purposes
-- Sandra: We may want to remove IGNORE if we use this for testing so we
-- understand when failures happen. 

PRAGMA foreign_keys = ON;

-- Seed example users
INSERT OR IGNORE INTO Users (id, display_name, email, timezone)
VALUES
  (1, 'Alice Developer', 'alice@example.com', 'UTC'),
  (2, 'Bob Tester', 'bob@example.com', 'UTC'),
  (3, 'Carol Manager', 'carol@example.com', 'UTC');

-- Seed a demo project
INSERT OR IGNORE INTO Projects (id, name, created_by)
VALUES
  (1, 'Demo Project', 3);

-- Seed a demo sprint for the project
INSERT OR IGNORE INTO Sprints (id, project_id, name, start_date, end_date, created_by)
VALUES
  (1, 1, 'Sprint 1', '2026-01-01', '2026-01-15', 3);

-- Seed basic board columns
INSERT OR IGNORE INTO Columns (id, project_id, name, key, position)
VALUES
  (1, 1, 'To Do', 'todo', 1),
  (2, 1, 'Blocked', 'blocked', 2),
  (3, 1, 'In Progress', 'in_progress', 3),
  (4, 1, 'In Review', 'in_review', 4),
  (5, 1, 'Complete', 'complete', 5);

-- Seed example tasks
INSERT OR IGNORE INTO Tasks (
  id, project_id, column_id, sprint_id, reporter_id, assignee_id, created_by, modified_by,
  title, description, start_date, due_date, position
)
VALUES
  (1, 1, 1, 1, 1, 2, 1, 2, 'Set up project', 'Initialize repo, CI and migrations', '2026-01-02', '2026-01-04', 0),
  (2, 1, 1, 1, 2, 2, 2, 2, 'Create tasks endpoint', 'Implement CRUD handlers for Tasks', '2026-01-03', '2026-01-07', 1),
  (3, 1, 2, 1, NULL, 1, NULL, NULL, 'Write docs', 'Add README notes for local dev', NULL, NULL, 2);

  -- Seed example comments
  INSERT OR IGNORE INTO Comments (
    id, task_id, created_by, content, created_at, updated_at
  )
  VALUES
    (1, 1, 2, 'This task has no AC.', '2026-01-05', '2026-01-05'),
    (2, 1, 3, 'Added AC.', '2026-01-06', '2026-01-06'),
    (3, 2, 1, 'This task should be on next sprint.', '2026-01-07', '2026-01-07');
